version: '3.9'

services:
  docker-mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=Fin
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=finuser
      - MYSQL_PASSWORD=F!nU$$3r54
    ports:
      - 3307:3306

  app:
    image: springio/fin:latest
    ports:
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker.for.mac.localhost:3306/Fin?createDatabaseIfNotExists=true&autoReconnect=true&useSSL=false
    depends_on:
      - docker-mysql
