dist: xenial
os: linux
jobs:
  include:
    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - node_modules
      script:
        - cd angularfrontend
        - npm install
        - ng build --prod
      before_install:
        - 'npm i -g firebase-tools'
      deploy:
        provider: script
        script: firebase deploy --token=${FIREBASE_TOKEN}
        skip_cleanup: true
        on:
          branch: master
    - language: java
      jdk: oraclejdk14
      services:
        - mysql
      before_install:
        - mysql -e 'CREATE DATABASE IF NOT EXISTS Fin;'
      script:
        - cd fin
        - mvn clean verify
