dist: xenial
os: linux
jobs:
  include:
    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - node_modules
      script:
        - cd angularfrontend
        - npm install
        - ng build
      before_install:
        - 'npm i -g firebase-tools'
      deploy:
        provider: script
        script: firebase deploy --token "1//0dwzJgxAXIaTWCgYIARAAGA0SNwF-L9IrT0A6dsOMR1TULb0NlZfIv7TAI-X3cdXl-Z2SGNHSrAS2HsxOfZMCbZtznn2bJlOR0Z8"
        skip_cleanup: true
        on:
          branch: master
    - language: java
      jdk: oraclejdk14
      script:
        - cd fin
        - mvn clean verify
