dist: xenial
os: linux
jobs:
  include:
    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - node_modules
      script:
        - cd angularfrontend
        - npm install
        - ng build
      deploy:
        provider: firebase
        token: $FIREBASE_TOKEN
    - language: java
      jdk: oraclejdk14
      script:
        - cd fin
        - mvn clean verify
